<script src="<?=base_url()?>assets/vendor/jquery/jquery.min.js"></script>
<script src="<?=base_url()?>assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?=base_url()?>assets/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="<?=base_url()?>assets/js/ruang-admin.min.js"></script>
<script src="<?=base_url()?>assets/scripts/AjaxRequest.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="<?=base_url()?>assets/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="<?=base_url()?>assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>
